name: Build ArduPilot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: arm-none-eabi-gcc
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
          release: '10.3-2021.10'
            
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          g++ \
          git \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          ninja-build
        python -m pip install --progress-bar off future lxml pymavlink MAVProxy pexpect flake8 geocoder empy==3.3.4 dronecan

    - name: Clone ArduPilot submodules
      run: |
        git submodule update --init --recursive

    - name: Build ArduPilot
      run: |
        ./waf configure --board CubeOrangePlus
        ./waf copter

    - name: Store build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ardupilot-build
        path: build/CubeOrangePlus/bin/
